spring:
    cloud:
        gcp:
            sql:
                enabled: true
                database-type: mysql
                database-name: marketplace
                instance-connection-name: ${DEVSHELL_PROJECT_ID:qwiklabs-gcp-01-3badb0128af2}:us-central1:mysql-db-container 