spring:
    cloud:
        gcp:
            sql:
                enabled: true
                database-type: mysql
                database-name: marketplace
                instance-connection-name: ${DEVSHELL_PROJECT_ID:qwiklabs-gcp-00-96ff96e16985}:us-central1:mysql-db-container 