spring:
    cloud:
        gcp:
            sql:
                enabled: true
                database-type: mysql
                database-name: marketplace
                instance-connection-name: ${DEVSHELL_PROJECT_ID:qwiklabs-gcp-00-34c80bd589b8}:us-central1:mysql-db-container 